In [18]:
import pandas as pd

In [19]:
df = pd.read_csv("customer_shopping_behavior.csv")

In [20]:
print(df.head)

<bound method NDFrame.head of       Customer ID  Age  Gender Item Purchased     Category  \
0               1   55    Male         Blouse     Clothing
1               2   19    Male        Sweater     Clothing
2               3   50    Male          Jeans     Clothing
3               4   21    Male        Sandals     Footwear
4               5   45    Male         Blouse     Clothing
...           ...  ...     ...            ...          ...
3895         3896   40  Female         Hoodie     Clothing
3896         3897   52  Female       Backpack  Accessories
3897         3898   46  Female           Belt  Accessories
3898         3899   44  Female          Shoes     Footwear
3899         3900   52  Female        Handbag  Accessories

      Purchase Amount (USD)       Location Size      Color  Season  \
0                        53       Kentucky    L       Gray  Winter
1                        64          Maine    L     Maroon  Winter
2                        73  Massachusetts    S     Maroon  Spring
3                        90   Rhode Island    M     Maroon  Spring
4                        49         Oregon    M  Turquoise  Spring
...                     ...            ...  ...        ...     ...
3895                     28       Virginia    L  Turquoise  Summer
3896                     49           Iowa    L      White  Spring
3897                     33     New Jersey    L      Green  Spring
3898                     77      Minnesota    S      Brown  Summer
3899                     81     California    M      Beige  Spring

      Review Rating Subscription Status   Shipping Type Discount Applied  \
0               3.1                 Yes         Express              Yes
1               3.1                 Yes         Express              Yes
2               3.1                 Yes   Free Shipping              Yes
3               3.5                 Yes    Next Day Air              Yes
4               2.7                 Yes   Free Shipping              Yes
...             ...                 ...             ...              ...
3895            4.2                  No  2-Day Shipping               No
3896            4.5                  No    Store Pickup               No
3897            2.9                  No        Standard               No
3898            3.8                  No         Express               No
3899            3.1                  No    Store Pickup               No

     Promo Code Used  Previous Purchases Payment Method Frequency of Purchases
0                Yes                  14          Venmo            Fortnightly
1                Yes                   2           Cash            Fortnightly
2                Yes                  23    Credit Card                 Weekly
3                Yes                  49         PayPal                 Weekly
4                Yes                  31         PayPal               Annually
...              ...                 ...            ...                    ...
3895              No                  32          Venmo                 Weekly
3896              No                  41  Bank Transfer              Bi-Weekly
3897              No                  24          Venmo              Quarterly
3898              No                  24          Venmo                 Weekly
3899              No                  33          Venmo              Quarterly

[3900 rows x 18 columns]>

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [6]:
df.describe(include="all")

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [7]:
df.isnull()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3896,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3897,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3898,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3899,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [8]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [14]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x : x.fillna(x.median()))

In [15]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [27]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')

In [30]:
labels = ['Young Adult', 'Adult', 'Middle-aged', 'Senior']
df['age_group'] = pd.qcut(df['age'],q=4, labels=labels)

In [40]:
df=df.drop(columns=['age group'])

In [41]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases', 'age_group'],
      dtype='object')

In [44]:
df[['age', 'age_group']].head(100)

    age    age_group
0    55  Middle-aged
1    19  Young Adult
2    50  Middle-aged
3    21  Young Adult
4    45  Middle-aged
..  ...          ...
95   37        Adult
96   32        Adult
97   21  Young Adult
98   20  Young Adult
99   26  Young Adult

[100 rows x 2 columns]

In [50]:
# column for frequency of purchases

frequency_mapping = {
    'Fortnightly' : 14,
    'Weekly' : 7,
    'Quarterly' : 90,
    'Monthly' : 30,
    'Bi-Weekly' : 14,
    'Annually' : 365,
    'After 3 months' : 90
}
df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [52]:
df[['purchase_frequency_days', 'frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                     14.0            Fortnightly
1                     14.0            Fortnightly
2                      7.0                 Weekly
3                      7.0                 Weekly
4                    365.0               Annually
5                      7.0                 Weekly
6                     90.0              Quarterly
7                      7.0                 Weekly
8                    365.0               Annually
9                     90.0              Quarterly

In [53]:
df[['discount_applied', 'promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [54]:
df['discount_applied'] == df['promo_code_used'].all()

0       False
1       False
2       False
3       False
4       False
        ...
3895    False
3896    False
3897    False
3898    False
3899    False
Name: discount_applied, Length: 3900, dtype: bool

In [57]:
df=df.drop('promo_code_used', axis=1)

In [66]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [62]:
pip install psycopg2-binary alchemy

Requirement already satisfied: psycopg2-binary in .\anaconda3\envs\plant_ml\lib\site-packages (2.9.11)
Requirement already satisfied: alchemy in .\anaconda3\envs\plant_ml\lib\site-packages (20.5)
Requirement already satisfied: requests==2.22.0 in .\anaconda3\envs\plant_ml\lib\site-packages (from alchemy) (2.22.0)
Requirement already satisfied: python-daemon==2.2.4 in .\anaconda3\envs\plant_ml\lib\site-packages (from alchemy) (2.2.4)
Requirement already satisfied: filelock==3.0.12 in .\anaconda3\envs\plant_ml\lib\site-packages (from alchemy) (3.0.12)
Requirement already satisfied: docutils in .\anaconda3\envs\plant_ml\lib\site-packages (from python-daemon==2.2.4->alchemy) (0.22.4)
Requirement already satisfied: lockfile>=0.10 in .\anaconda3\envs\plant_ml\lib\site-packages (from python-daemon==2.2.4->alchemy) (0.12.2)
Requirement already satisfied: setuptools in .\anaconda3\envs\plant_ml\lib\site-packages (from python-daemon==2.2.4->alchemy) (80.10.2)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in .\anaconda3\envs\plant_ml\lib\site-packages (from requests==2.22.0->alchemy) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in .\anaconda3\envs\plant_ml\lib\site-packages (from requests==2.22.0->alchemy) (2.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in .\anaconda3\envs\plant_ml\lib\site-packages (from requests==2.22.0->alchemy) (1.25.11)
Requirement already satisfied: certifi>=2017.4.17 in .\anaconda3\envs\plant_ml\lib\site-packages (from requests==2.22.0->alchemy) (2026.2.25)
Note: you may need to restart the kernel to use updated packages.

In [67]:
!pip install pymysql sqlalchemy

Collecting pymysql
  Downloading pymysql-1.1.2-py3-none-any.whl.metadata (4.3 kB)
Collecting sqlalchemy
  Downloading sqlalchemy-2.0.48-cp310-cp310-win_amd64.whl.metadata (9.8 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.3.2-cp310-cp310-win_amd64.whl.metadata (3.8 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in .\anaconda3\envs\plant_ml\lib\site-packages (from sqlalchemy) (4.15.0)
Downloading pymysql-1.1.2-py3-none-any.whl (45 kB)
Downloading sqlalchemy-2.0.48-cp310-cp310-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   --------- ------------------------------ 0.5/2.1 MB 16.5 kB/s eta 0:01:39
   --------- ------------------------------ 0.5/2.1 MB 16.5 kB/s eta 0:01:39
   --------- ------------------------------ 0.5/2.1 MB 16.5 kB/s eta 0:01:39
   --------- ------------------------------ 0.5/2.1 MB 16.5 kB/s eta 0:01:39
   --------- ------------------------------ 0.5/2.1 MB 16.5 kB/s eta 0:01:39
   --------- ------------------------------ 0.5/2.1 MB 16.5 kB/s eta 0:01:39
   --------- ------------------------------ 0.5/2.1 MB 16.5 kB/s eta 0:01:39
   --------- ------------------------------ 0.5/2.1 MB 16.5 kB/s eta 0:01:39
   --------- ------------------------------ 0.5/2.1 MB 16.5 kB/s eta 0:01:39
   --------- ------------------------------ 0.5/2.1 MB 16.5 kB/s eta 0:01:39
   --------- ------------------------------ 0.5/2.1 MB 16.5 kB/s eta 0:01:39
   --------- ------------------------------ 0.5/2.1 MB 16.5 kB/s eta 0:01:39
   --------- ------------------------------ 0.5/2.1 MB 16.5 kB/s eta 0:01:39
   --------- ------------------------------ 0.5/2.1 MB 16.5 kB/s eta 0:01:39
   --------- ------------------------------ 0.5/2.1 MB 16.5 kB/s eta 0:01:39
   --------- ------------------------------ 0.5/2.1 MB 16.5 kB/s eta 0:01:39
   --------- ------------------------------ 0.5/2.1 MB 16.5 kB/s eta 0:01:39
   --------- ------------------------------ 0.5/2.1 MB 16.5 kB/s eta 0:01:39
   --------- ------------------------------ 0.5/2.1 MB 16.5 kB/s eta 0:01:39
   --------- ------------------------------ 0.5/2.1 MB 16.5 kB/s eta 0:01:39
   --------- ------------------------------ 0.5/2.1 MB 16.5 kB/s eta 0:01:39
   --------- ------------------------------ 0.5/2.1 MB 16.5 kB/s eta 0:01:39
   --------- ------------------------------ 0.5/2.1 MB 16.5 kB/s eta 0:01:39
   --------- ------------------------------ 0.5/2.1 MB 16.5 kB/s eta 0:01:39
   --------- ------------------------------ 0.5/2.1 MB 16.5 kB/s eta 0:01:39
   --------- ------------------------------ 0.5/2.1 MB 16.5 kB/s eta 0:01:39
   --------- ------------------------------ 0.5/2.1 MB 16.5 kB/s eta 0:01:39
   --------- ------------------------------ 0.5/2.1 MB 16.5 kB/s eta 0:01:39
   --------- ------------------------------ 0.5/2.1 MB 16.5 kB/s eta 0:01:39
   --------- ------------------------------ 0.5/2.1 MB 16.5 kB/s eta 0:01:39
   --------- ------------------------------ 0.5/2.1 MB 16.5 kB/s eta 0:01:39
   --------- ------------------------------ 0.5/2.1 MB 16.5 kB/s eta 0:01:39
   --------- ------------------------------ 0.5/2.1 MB 16.5 kB/s eta 0:01:39
   --------- ------------------------------ 0.5/2.1 MB 16.5 kB/s eta 0:01:39
   --------- ------------------------------ 0.5/2.1 MB 16.5 kB/s eta 0:01:39
   --------- ------------------------------ 0.5/2.1 MB 16.5 kB/s eta 0:01:39
   --------- ------------------------------ 0.5/2.1 MB 16.5 kB/s eta 0:01:39
   --------- ------------------------------ 0.5/2.1 MB 16.5 kB/s eta 0:01:39
   --------- ------------------------------ 0.5/2.1 MB 16.5 kB/s eta 0:01:39
   --------- ------------------------------ 0.5/2.1 MB 16.5 kB/s eta 0:01:39
   --------- ------------------------------ 0.5/2.1 MB 16.5 kB/s eta 0:01:39
   --------- ------------------------------ 0.5/2.1 MB 16.5 kB/s eta 0:01:39
   --------- ------------------------------ 0.5/2.1 MB 16.5 kB/s eta 0:01:39
   --------- ------------------------------ 0.5/2.1 MB 16.5 kB/s eta 0:01:39
   --------- ------------------------------ 0.5/2.1 MB 16.5 kB/s eta 0:01:39
   --------- ------------------------------ 0.5/2.1 MB 16.5 kB/s eta 0:01:39
   --------- ------------------------------ 0.5/2.1 MB 16.5 kB/s eta 0:01:39
   --------- ------------------------------ 0.5/2.1 MB 16.5 kB/s eta 0:01:39
   --------- ------------------------------ 0.5/2.1 MB 16.5 kB/s eta 0:01:39
   --------- ------------------------------ 0.5/2.1 MB 16.5 kB/s eta 0:01:39
   --------- ------------------------------ 0.5/2.1 MB 16.5 kB/s eta 0:01:39
   --------- ------------------------------ 0.5/2.1 MB 16.5 kB/s eta 0:01:39
   --------- ------------------------------ 0.5/2.1 MB 16.5 kB/s eta 0:01:39
   --------- ------------------------------ 0.5/2.1 MB 16.5 kB/s eta 0:01:39
   --------- ------------------------------ 0.5/2.1 MB 16.5 kB/s eta 0:01:39
   --------- ------------------------------ 0.5/2.1 MB 16.5 kB/s eta 0:01:39
   --------- ------------------------------ 0.5/2.1 MB 16.5 kB/s eta 0:01:39
   --------- ------------------------------ 0.5/2.1 MB 16.5 kB/s eta 0:01:39
   --------- ------------------------------ 0.5/2.1 MB 16.5 kB/s eta 0:01:39
   --------- ------------------------------ 0.5/2.1 MB 16.5 kB/s eta 0:01:39
   -------------- ------------------------- 0.8/2.1 MB 18.3 kB/s eta 0:01:15
   -------------- ------------------------- 0.8/2.1 MB 18.3 kB/s eta 0:01:15
   -------------- ------------------------- 0.8/2.1 MB 18.3 kB/s eta 0:01:15
   -------------- ------------------------- 0.8/2.1 MB 18.3 kB/s eta 0:01:15
   -------------- ------------------------- 0.8/2.1 MB 18.3 kB/s eta 0:01:15
   -------------- ------------------------- 0.8/2.1 MB 18.3 kB/s eta 0:01:15
   -------------- ------------------------- 0.8/2.1 MB 18.3 kB/s eta 0:01:15
   -------------- ------------------------- 0.8/2.1 MB 18.3 kB/s eta 0:01:15
   -------------- ------------------------- 0.8/2.1 MB 18.3 kB/s eta 0:01:15
   -------------- ------------------------- 0.8/2.1 MB 18.3 kB/s eta 0:01:15
   -------------- ------------------------- 0.8/2.1 MB 18.3 kB/s eta 0:01:15
   -------------- ------------------------- 0.8/2.1 MB 18.3 kB/s eta 0:01:15
   -------------- ------------------------- 0.8/2.1 MB 18.3 kB/s eta 0:01:15
   -------------- ------------------------- 0.8/2.1 MB 18.3 kB/s eta 0:01:15
   -------------- ------------------------- 0.8/2.1 MB 18.3 kB/s eta 0:01:15
   -------------- ------------------------- 0.8/2.1 MB 18.3 kB/s eta 0:01:15
   -------------- ------------------------- 0.8/2.1 MB 18.3 kB/s eta 0:01:15
   -------------- ------------------------- 0.8/2.1 MB 18.3 kB/s eta 0:01:15
   -------------- ------------------------- 0.8/2.1 MB 18.3 kB/s eta 0:01:15
   -------------- ------------------------- 0.8/2.1 MB 18.3 kB/s eta 0:01:15
   -------------- ------------------------- 0.8/2.1 MB 18.3 kB/s eta 0:01:15
   -------------- ------------------------- 0.8/2.1 MB 18.3 kB/s eta 0:01:15
   -------------- ------------------------- 0.8/2.1 MB 18.3 kB/s eta 0:01:15
   -------------- ------------------------- 0.8/2.1 MB 18.3 kB/s eta 0:01:15
   -------------- ------------------------- 0.8/2.1 MB 18.3 kB/s eta 0:01:15
   -------------- ------------------------- 0.8/2.1 MB 18.3 kB/s eta 0:01:15
   -------------- ------------------------- 0.8/2.1 MB 18.3 kB/s eta 0:01:15
   -------------- ------------------------- 0.8/2.1 MB 18.3 kB/s eta 0:01:15
   -------------- ------------------------- 0.8/2.1 MB 18.3 kB/s eta 0:01:15
   -------------- ------------------------- 0.8/2.1 MB 18.3 kB/s eta 0:01:15
   -------------- ------------------------- 0.8/2.1 MB 18.3 kB/s eta 0:01:15
   -------------- ------------------------- 0.8/2.1 MB 18.3 kB/s eta 0:01:15
   -------------- ------------------------- 0.8/2.1 MB 18.3 kB/s eta 0:01:15
   -------------- ------------------------- 0.8/2.1 MB 18.3 kB/s eta 0:01:15
   -------------- ------------------------- 0.8/2.1 MB 18.3 kB/s eta 0:01:15
   -------------- ------------------------- 0.8/2.1 MB 18.3 kB/s eta 0:01:15
   -------------- ------------------------- 0.8/2.1 MB 18.3 kB/s eta 0:01:15
   -------------- ------------------------- 0.8/2.1 MB 18.3 kB/s eta 0:01:15
   -------------- ------------------------- 0.8/2.1 MB 18.3 kB/s eta 0:01:15
   -------------- ------------------------- 0.8/2.1 MB 18.3 kB/s eta 0:01:15
   -------------- ------------------------- 0.8/2.1 MB 18.3 kB/s eta 0:01:15
   -------------- ------------------------- 0.8/2.1 MB 18.3 kB/s eta 0:01:15
   -------------- ------------------------- 0.8/2.1 MB 18.3 kB/s eta 0:01:15
   -------------- ------------------------- 0.8/2.1 MB 18.3 kB/s eta 0:01:15
   -------------- ------------------------- 0.8/2.1 MB 18.3 kB/s eta 0:01:15
   -------------- ------------------------- 0.8/2.1 MB 18.3 kB/s eta 0:01:15
   -------------- ------------------------- 0.8/2.1 MB 18.3 kB/s eta 0:01:15
   -------------- ------------------------- 0.8/2.1 MB 18.3 kB/s eta 0:01:15
   -------------- ------------------------- 0.8/2.1 MB 18.3 kB/s eta 0:01:15
   -------------- ------------------------- 0.8/2.1 MB 18.3 kB/s eta 0:01:15
   -------------- ------------------------- 0.8/2.1 MB 18.3 kB/s eta 0:01:15
   -------------- ------------------------- 0.8/2.1 MB 18.3 kB/s eta 0:01:15
   ------------------- -------------------- 1.0/2.1 MB 20.3 kB/s eta 0:00:54
   ------------------- -------------------- 1.0/2.1 MB 20.3 kB/s eta 0:00:54
   ------------------- -------------------- 1.0/2.1 MB 20.3 kB/s eta 0:00:54
   ------------------- -------------------- 1.0/2.1 MB 20.3 kB/s eta 0:00:54
   ------------------- -------------------- 1.0/2.1 MB 20.3 kB/s eta 0:00:54
   ------------------- -------------------- 1.0/2.1 MB 20.3 kB/s eta 0:00:54
   ------------------- -------------------- 1.0/2.1 MB 20.3 kB/s eta 0:00:54
   ------------------- -------------------- 1.0/2.1 MB 20.3 kB/s eta 0:00:54
   ------------------- -------------------- 1.0/2.1 MB 20.3 kB/s eta 0:00:54
   ------------------- -------------------- 1.0/2.1 MB 20.3 kB/s eta 0:00:54
   ------------------- -------------------- 1.0/2.1 MB 20.3 kB/s eta 0:00:54
   ------------------- -------------------- 1.0/2.1 MB 20.3 kB/s eta 0:00:54
   ------------------- -------------------- 1.0/2.1 MB 20.3 kB/s eta 0:00:54
   ------------------- -------------------- 1.0/2.1 MB 20.3 kB/s eta 0:00:54
   ------------------- -------------------- 1.0/2.1 MB 20.3 kB/s eta 0:00:54
   ------------------- -------------------- 1.0/2.1 MB 20.3 kB/s eta 0:00:54
   ------------------- -------------------- 1.0/2.1 MB 20.3 kB/s eta 0:00:54
   ------------------- -------------------- 1.0/2.1 MB 20.3 kB/s eta 0:00:54
   ------------------- -------------------- 1.0/2.1 MB 20.3 kB/s eta 0:00:54
   ------------------- -------------------- 1.0/2.1 MB 20.3 kB/s eta 0:00:54
   ------------------- -------------------- 1.0/2.1 MB 20.3 kB/s eta 0:00:54
   ------------------- -------------------- 1.0/2.1 MB 20.3 kB/s eta 0:00:54
   ------------------- -------------------- 1.0/2.1 MB 20.3 kB/s eta 0:00:54
   ------------------- -------------------- 1.0/2.1 MB 20.3 kB/s eta 0:00:54

In [72]:

from sqlalchemy import create_engine

username = "postgres"      
password = "Shikha$820" 
host = "localhost"         
port = "5432"              
database = "customer_behavior"    

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")


table_name = "customer"   
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'customer' in database 'customer_behavior'.